# Generated by Django 5.0.6 on 2024-05-17 10:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchHist',
            new_name='SearchHistory',
        ),
    ]
