# Generated by Django 5.0.6 on 2024-05-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0002_rename_searchhist_searchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='search_term',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
