# Generated by Django 5.0.6 on 2024-05-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps_app', '0003_alter_searchhistory_search_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='search_term',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
